# Generated by Django 5.1.4 on 2026-06-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trainerprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('player', 'Player'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
